### ISSUE TITLE
Npm install error

### ISSUE THREAD

**Issue by JayKan** [makebrainwaves/BrainWaves#16]
<img width="1094" alt="screen shot 2018-07-31 at 8 38 27 pm" src="https://user-images.githubusercontent.com/1400300/43499718-c0c8f014-9501-11e8-9b3f-b1bc425fc6c5.png">

**Comment by jdpigeon** [comment]
You're on Mac, right?

Setting up a computer to be able to run node-gyp builds can get pretty brutal. For Mac, it looks like the most important thing is to have the Xcode tools and installed and make sure npm is using Python 2.7 (there's a command to point it to a specific python install, can't remember off the top of my head)
https://github.com/nodejs/node-gyp

**Comment by teonbrooks** [comment]
closing bug since likely problem is identified and with solution. please re-open if this problem is persistent.
