### ISSUE TITLE
Module not found 'jspsych-react'

### ISSUE THREAD

**Issue by alexandrebarachant** [makebrainwaves/BrainWaves#3]
When running the app, i get this error

```
ERROR in ./app/components/ExperimentRun.js
Module not found: Error: Can't resolve 'jspsych-react'
```

**Comment by alexandrebarachant** [comment]
Thanks. It works for me. Feel free to close the issue but I would suggest to keep it open until this is documented

**Comment by jdpigeon** [comment]
Thanks Jay for answering this!

We're going to be putting jspsych-react on npm very soon. So hopefully this problem won't be around much longer

**Comment by teonbrooks** [comment]
@jdpigeon, is there anything in particular we wanted to do to jspsych-react. I could just do a 0.1.0 release of it so it could be a regular dependency
