### ISSUE TITLE
Cannot find module 'bluetooth-hci-socket'

### ISSUE THREAD

**Issue by jdpigeon** [makebrainwaves/BrainWaves#32]
This error is encountered upon try to build the app from source on a new installation of Ubuntu 16 running Node 10.

The solution appears to be two part:

1. Downgrade node (I was successful with v8.11.1). This is trivial with nvm. https://github.com/noble/node-bluetooth-hci-socket/issues/84

2. Install python 2 and make sure the node is configured to point to this installation. This is necessary in order for node-gyp to work, which builds native dependencies such as bluetooth-hci-socket. https://github.com/nodejs/node-gyp/issues/1337

**Comment by teonbrooks** [comment]
`bluetooth-hci-socket` is a dependence on `bleat`. `bleat` has been deprecated for `webbluetooth`. #77 aims to remove these dependencies. final testing needs to be done on Windows; it has been updated to support webbluetooth in the latest electron

**Comment by teonbrooks** [comment]
closing bc of #131 completion. if this wasn't solved, please reopen
