### ISSUE TITLE
Missing keys from utils/emotiv

### ISSUE THREAD

**Issue by JayKan** [makebrainwaves/BrainWaves#5]
See attached screenshot:

<img width="921" alt="screen shot 2018-07-16 at 4 34 57 am" src="https://user-images.githubusercontent.com/1400300/42756800-8e3a5ca6-88b2-11e8-84b6-5a55b652e25f.png">

**Comment by jdpigeon** [comment]
We can't just give our secret (extremely expensive) emotiv keys away to anyone :)

Any suggestions on how we could still allow people to build the app from source without the keys? Muse is fully supported as well, so it'd be nice to be able to just disable all Emotiv features when it detects no keys exist.

**Comment by alexandrebarachant** [comment]
yeah, would be nice to detect if the key are there, and skip them if they are not.

Alternatively, creating a fake (empty) keys file could do the job.

**Comment by alexandrebarachant** [comment]
Okay, i created an empty `keys` file on the root of the repository. that allowed me to run the app
