### ISSUE TITLE
Recording Behavioral Data with No EEG

### ISSUE THREAD

**Issue by sazeka** [makebrainwaves/BrainWaves#51]
The BrainWaves app doesn't record the behavioural data when the EEG feature is disabled in the custom setting.

**Comment by jdpigeon** [comment]
I'm not able to replicate this. When running experiments with EEG both enabled and disabled I am seeing data getting stored in `BrainWaves Workspaces/Experiment/Data/Subject/Behavior` as csv files on Windows 10.

**Comment by sdikker** [comment]
related to this: it would be great if data was still recorded even if none of the electrodes have connectivity: just for testing purposes
