### ISSUE TITLE
Look into way to replace Python dependency (or simplify python environment installation)

### ISSUE THREAD

**Issue by jdpigeon** [makebrainwaves/BrainWaves#64]
The biggest thing stopping the app from scaling is the Anaconda environment set up step that is too complicated for most people to do by themselves. We could either get around this issue by replacing MNE type code with JS or by simplifying or encapusulating the Python aspects of the codebase in a more easily installable way

**Comment by teonbrooks** [comment]
closed by https://github.com/makebrainwaves/BrainWaves/pull/65
