### ISSUE TITLE
Pyodide archive issues in node on windows 10

### ISSUE THREAD

**Issue by jdpigeon** [makebrainwaves/BrainWaves#78]
I tried to write a cross-platform node script that would handle downloading and unzipping pyodide. However, I've gotten stuck on what appear to be archive corruption issues. 

working on a dano-pyodide-install and getting 
```
Error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
    at Object.exports.decode (C:\Users\dano_uyjp0ey\teon\BrainWaves\node_modules\tar-fs\node_modules\tar-stream\headers.js:267:43)
```

Is there another more windows friendly archive that we could use?

**Comment by jdpigeon** [comment]
Lol, it looks like this issue might be entirely because I was tryping to decrypt the archive with gzip encoding rather than bzip encoding.

Such oversight is the price you pay for coding at the biergarten

**Comment by sdikker** [comment]
Ha! #remoteoffice

Suzanne Dikker
+1-212-920-4348
