### ISSUE TITLE
Separate labjs component into separate repo

### ISSUE THREAD

**Issue by teonbrooks** [makebrainwaves/BrainWaves#87]
A few things:
1. Could you open a PR with the branch so that I could make some comments on the code.
2. I think we would like to echo the structure of the jspsych-react component with the props given there. I think you can keep the name `Experiment`, or maybe we should change both to `ExperimentWindow`
3. the labjs component has the lab.js files included instead having them in the package.json file. It's likely that we would want to maintain the current version of lab.js so I would suggest adding it there

**Comment by Yury-Shevchenko** [comment]
1. I've opened "Lab.js integration" PR
2. Changed it to ExperimentWindow
3. I guess, we have to discuss how to turn it to package.json file - it's not clear for me now what exactly you mean.

**Comment by teonbrooks** [comment]
closing because lab.js is now served via npm and the React component we create from it isn't particularly custom, just window sizing. Not necessary for separate repo maintenance
